name: safetrack
description: SafeTrack - IoT GPS Vehicle Tracking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.0
  # Utilities
  uuid: ^4.0.0
  intl: ^0.18.0
  latlong2: ^0.9.0
  flutter_animate: ^4.2.0
  # Map
  flutter_map: ^6.0.0
  http: ^1.0.0
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
