[general]
log_level=4

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@chirpstack-postgres/chirpstack_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server]

  [application_server.api]
  public_host="chirpstack-app-server:8001"

  [application_server.external_api]
  bind="0.0.0.0:8080"
  jwt_secret="verysecretkey"

[join_server]
bind="0.0.0.0:8003"

[network_server]
server="chirpstack-network-server:8000"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"
